// Generated by contrast.py - worst-case light tokens per Lmin (see contrast-tables.md).
const WORST = {
 "0.40": {
  "text-dim": "#6e6a64",
  "text-faint": "#a29d95",
  "copper-bright": "#9c6d20",
  "warning-bright": "#6f4c02",
  "eyebrow-0": "#97691f",
  "eyebrow-1": "#cf9c45",
  "readout-0": "#dca136",
  "readout-1": "#f3cf7c"
 },
 "0.50": {
  "text-dim": "#211d18",
  "text-faint": "#a29d95",
  "copper-bright": "#2f1c00",
  "warning-bright": "#3c2700",
  "eyebrow-0": "#97691f",
  "eyebrow-1": "#cf9c45",
  "readout-0": "#dca136",
  "readout-1": "#f3cf7c"
 },
 "0.60": {
  "text-dim": "#38352f",
  "text-faint": "#a29d95",
  "copper-bright": "#492f02",
  "warning-bright": "#533801",
  "eyebrow-0": "#97691f",
  "eyebrow-1": "#cf9c45",
  "readout-0": "#dca136",
  "readout-1": "#f3cf7c"
 },
 "0.65": {
  "text-dim": "#423e39",
  "text-faint": "#423e37",
  "copper-bright": "#553703",
  "warning-bright": "#5d4006",
  "eyebrow-0": "#211200",
  "eyebrow-1": "#553902",
  "readout-0": "#dca136",
  "readout-1": "#f3cf7c"
 },
 "0.70": {
  "text-dim": "#4b4741",
  "text-faint": "#4b4740",
  "copper-bright": "#603f01",
  "warning-bright": "#674602",
  "eyebrow-0": "#2b1a01",
  "eyebrow-1": "#614200",
  "readout-0": "#dca136",
  "readout-1": "#f3cf7c"
 },
 "0.80": {
  "text-dim": "#5b5752",
  "text-faint": "#5c5750",
  "copper-bright": "#734d07",
  "warning-bright": "#7a5407",
  "eyebrow-0": "#3f2700",
  "eyebrow-1": "#75520a",
  "readout-0": "#dca136",
  "readout-1": "#f3cf7c"
 },
 "0.90": {
  "text-dim": "#6b6761",
  "text-faint": "#6c6760",
  "copper-bright": "#855a0b",
  "warning-bright": "#8c6108",
  "eyebrow-0": "#503401",
  "eyebrow-1": "#8a5f00",
  "readout-0": "#805906",
  "readout-1": "#a17f28"
 },
 "1.00": {
  "text-dim": "#6e6a64",
  "text-faint": "#7b766e",
  "copper-bright": "#966718",
  "warning-bright": "#9e6d04",
  "eyebrow-0": "#634000",
  "eyebrow-1": "#9c6e11",
  "readout-0": "#95680a",
  "readout-1": "#b3903c"
 }
};
